export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';

export const USERS_POSTING = 'USERS_POSTING';
export const USERS_POST_SUCCESS = 'USERS_POST_SUCCESS';
